# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lr3.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 556)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 170, 771, 291))
        self.tabWidget.setObjectName("tabWidget")
        self.tabHead = QtWidgets.QWidget()
        self.tabHead.setObjectName("tabHead")
        self.position = QtWidgets.QLineEdit(self.tabHead)
        self.position.setGeometry(QtCore.QRect(10, 30, 581, 25))
        self.position.setObjectName("position")
        self.label_14 = QtWidgets.QLabel(self.tabHead)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 251, 17))
        self.label_14.setObjectName("label_14")
        self.FIO = QtWidgets.QLineEdit(self.tabHead)
        self.FIO.setGeometry(QtCore.QRect(10, 60, 581, 25))
        self.FIO.setObjectName("FIO")
        self.label_18 = QtWidgets.QLabel(self.tabHead)
        self.label_18.setGeometry(QtCore.QRect(10, 90, 301, 17))
        self.label_18.setObjectName("label_18")
        self.headPosition = QtWidgets.QLineEdit(self.tabHead)
        self.headPosition.setGeometry(QtCore.QRect(10, 110, 581, 25))
        self.headPosition.setObjectName("headPosition")
        self.headFullName = QtWidgets.QLineEdit(self.tabHead)
        self.headFullName.setGeometry(QtCore.QRect(10, 140, 581, 25))
        self.headFullName.setObjectName("headFullName")
        self.label_19 = QtWidgets.QLabel(self.tabHead)
        self.label_19.setGeometry(QtCore.QRect(610, 10, 141, 17))
        self.label_19.setObjectName("label_19")
        self.dateCreate = QtWidgets.QDateEdit(self.tabHead)
        self.dateCreate.setGeometry(QtCore.QRect(630, 30, 131, 26))
        self.dateCreate.setObjectName("dateCreate")
        self.label_7 = QtWidgets.QLabel(self.tabHead)
        self.label_7.setGeometry(QtCore.QRect(610, 50, 141, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tabHead)
        self.label_8.setGeometry(QtCore.QRect(630, 70, 20, 31))
        self.label_8.setObjectName("label_8")
        self.reportForm = QtWidgets.QDateEdit(self.tabHead)
        self.reportForm.setGeometry(QtCore.QRect(650, 70, 110, 26))
        self.reportForm.setObjectName("reportForm")
        self.label_9 = QtWidgets.QLabel(self.tabHead)
        self.label_9.setGeometry(QtCore.QRect(630, 90, 20, 31))
        self.label_9.setObjectName("label_9")
        self.reportOn = QtWidgets.QDateEdit(self.tabHead)
        self.reportOn.setGeometry(QtCore.QRect(650, 90, 110, 26))
        self.reportOn.setObjectName("reportOn")
        self.label_20 = QtWidgets.QLabel(self.tabHead)
        self.label_20.setGeometry(QtCore.QRect(610, 120, 141, 17))
        self.label_20.setObjectName("label_20")
        self.typeOperation = QtWidgets.QSpinBox(self.tabHead)
        self.typeOperation.setGeometry(QtCore.QRect(630, 140, 131, 26))
        self.typeOperation.setMaximum(999999999)
        self.typeOperation.setObjectName("typeOperation")
        self.tabWidget.addTab(self.tabHead, "")
        self.tabMain = QtWidgets.QWidget()
        self.tabMain.setStyleSheet("")
        self.tabMain.setObjectName("tabMain")
        self.tblMain = QtWidgets.QTableWidget(self.tabMain)
        self.tblMain.setGeometry(QtCore.QRect(0, 0, 771, 261))
        self.tblMain.setObjectName("tblMain")
        self.tblMain.setColumnCount(7)
        self.tblMain.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblMain.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMain.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMain.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMain.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMain.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMain.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMain.setHorizontalHeaderItem(6, item)
        self.tabWidget.addTab(self.tabMain, "")
        self.tabFight = QtWidgets.QWidget()
        self.tabFight.setObjectName("tabFight")
        self.tblFight = QtWidgets.QTableWidget(self.tabFight)
        self.tblFight.setGeometry(QtCore.QRect(0, 0, 771, 271))
        self.tblFight.setObjectName("tblFight")
        self.tblFight.setColumnCount(7)
        self.tblFight.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblFight.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFight.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFight.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFight.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFight.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFight.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFight.setHorizontalHeaderItem(6, item)
        self.tabWidget.addTab(self.tabFight, "")
        self.tabLost = QtWidgets.QWidget()
        self.tabLost.setObjectName("tabLost")
        self.tblLost = QtWidgets.QTableWidget(self.tabLost)
        self.tblLost.setGeometry(QtCore.QRect(0, 0, 771, 271))
        self.tblLost.setObjectName("tblLost")
        self.tblLost.setColumnCount(7)
        self.tblLost.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblLost.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLost.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLost.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLost.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLost.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLost.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLost.setHorizontalHeaderItem(6, item)
        self.tabWidget.addTab(self.tabLost, "")
        self.tabFut = QtWidgets.QWidget()
        self.tabFut.setObjectName("tabFut")
        self.label_10 = QtWidgets.QLabel(self.tabFut)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 561, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tabFut)
        self.label_11.setGeometry(QtCore.QRect(90, 30, 281, 21))
        self.label_11.setObjectName("label_11")
        self.cntCrushSee = QtWidgets.QSpinBox(self.tabFut)
        self.cntCrushSee.setGeometry(QtCore.QRect(10, 30, 71, 26))
        self.cntCrushSee.setMaximum(999999999)
        self.cntCrushSee.setObjectName("cntCrushSee")
        self.label_12 = QtWidgets.QLabel(self.tabFut)
        self.label_12.setGeometry(QtCore.QRect(10, 60, 131, 17))
        self.label_12.setObjectName("label_12")
        self.tblCommis = QtWidgets.QTableWidget(self.tabFut)
        self.tblCommis.setGeometry(QtCore.QRect(10, 80, 431, 171))
        self.tblCommis.setObjectName("tblCommis")
        self.tblCommis.setColumnCount(3)
        self.tblCommis.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblCommis.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCommis.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCommis.setHorizontalHeaderItem(2, item)
        self.label_13 = QtWidgets.QLabel(self.tabFut)
        self.label_13.setGeometry(QtCore.QRect(460, 60, 191, 17))
        self.label_13.setObjectName("label_13")
        self.adminDecis = QtWidgets.QPlainTextEdit(self.tabFut)
        self.adminDecis.setGeometry(QtCore.QRect(460, 80, 301, 171))
        self.adminDecis.setObjectName("adminDecis")
        self.tabWidget.addTab(self.tabFut, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 101, 17))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 211, 17))
        self.label_3.setObjectName("label_3")
        self.dateEditAct = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditAct.setGeometry(QtCore.QRect(460, 10, 131, 26))
        self.dateEditAct.setObjectName("dateEditAct")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 10, 51, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(420, 10, 41, 31))
        self.label_6.setObjectName("label_6")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(650, 60, 121, 20))
        self.label_16.setObjectName("label_16")
        self.numOrg = QtWidgets.QSpinBox(self.centralwidget)
        self.numOrg.setGeometry(QtCore.QRect(650, 80, 131, 26))
        self.numOrg.setMaximum(999999999)
        self.numOrg.setObjectName("numOrg")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(600, 160, 51, 31))
        self.label_17.setObjectName("label_17")
        self.OKDP = QtWidgets.QSpinBox(self.centralwidget)
        self.OKDP.setGeometry(QtCore.QRect(650, 160, 131, 26))
        self.OKDP.setMaximum(999999999)
        self.OKDP.setObjectName("OKDP")
        self.cmbOrg = QtWidgets.QComboBox(self.centralwidget)
        self.cmbOrg.setGeometry(QtCore.QRect(10, 80, 631, 25))
        self.cmbOrg.setObjectName("cmbOrg")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(650, 110, 121, 20))
        self.label_21.setObjectName("label_21")
        self.numStruct = QtWidgets.QSpinBox(self.centralwidget)
        self.numStruct.setGeometry(QtCore.QRect(650, 130, 131, 26))
        self.numStruct.setMaximum(999999999)
        self.numStruct.setObjectName("numStruct")
        self.cmbStruct = QtWidgets.QComboBox(self.centralwidget)
        self.cmbStruct.setGeometry(QtCore.QRect(10, 130, 631, 25))
        self.cmbStruct.setObjectName("cmbStruct")
        self.exportExcel = QtWidgets.QPushButton(self.centralwidget)
        self.exportExcel.setGeometry(QtCore.QRect(10, 480, 101, 31))
        self.exportExcel.setObjectName("exportExcel")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(680, 480, 101, 31))
        self.exit.setObjectName("exit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 40, 341, 17))
        self.label_2.setObjectName("label_2")
        self.numAct = QtWidgets.QSpinBox(self.centralwidget)
        self.numAct.setGeometry(QtCore.QRect(280, 10, 131, 26))
        self.numAct.setMaximum(999999999)
        self.numAct.setObjectName("numAct")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ОП-8"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.position.setText(_translate("MainWindow", "Должность"))
        self.label_14.setText(_translate("MainWindow", "Материально ответственное лицо:"))
        self.FIO.setText(_translate("MainWindow", "Ф.И.О"))
        self.label_18.setText(_translate("MainWindow", "Руководитель:"))
        self.headPosition.setText(_translate("MainWindow", "Должность"))
        self.headFullName.setText(_translate("MainWindow", "Расшифровка подписи"))
        self.label_19.setText(_translate("MainWindow", "Дата создания"))
        self.label_7.setText(_translate("MainWindow", "Отчетный период"))
        self.label_8.setText(_translate("MainWindow", "С"))
        self.label_9.setText(_translate("MainWindow", "По"))
        self.label_20.setText(_translate("MainWindow", "Вид операции"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHead), _translate("MainWindow", "Шапка"))
        item = self.tblMain.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Наименование"))
        item = self.tblMain.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Код"))
        item = self.tblMain.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Цена, руб. коп."))
        item = self.tblMain.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Примечание"))
        item = self.tblMain.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Кол-во всего"))
        item = self.tblMain.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Сумма всего"))
        item = self.tblMain.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("MainWindow", "Главная"))
        item = self.tblFight.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Наименование"))
        item = self.tblFight.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Кол-во"))
        item = self.tblFight.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Сумма, руб. коп."))
        item = self.tblFight.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Обстоятельство"))
        item = self.tblFight.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Кол-во всего"))
        item = self.tblFight.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Сумма всего"))
        item = self.tblFight.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFight), _translate("MainWindow", "Бой, лом"))
        item = self.tblLost.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Наименование"))
        item = self.tblLost.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Кол-во"))
        item = self.tblLost.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Сумма, руб. коп."))
        item = self.tblLost.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Обстоятельство"))
        item = self.tblLost.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Кол-во всего"))
        item = self.tblLost.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Сумма всего"))
        item = self.tblLost.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLost), _translate("MainWindow", "Утрачено, пропало"))
        self.label_10.setText(_translate("MainWindow", "Перечисленные в графе \"Бой, лом\" столовая посуда и приборы в количестве"))
        self.label_11.setText(_translate("MainWindow", "шт. уничтожены в нашем пристуствии"))
        self.label_12.setText(_translate("MainWindow", "Члены комиссии:"))
        item = self.tblCommis.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Должность"))
        item = self.tblCommis.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Расшифровка подписи"))
        item = self.tblCommis.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Удалить"))
        self.label_13.setText(_translate("MainWindow", "Решение администрации"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFut), _translate("MainWindow", "Заключение"))
        self.label.setText(_translate("MainWindow", "Организация:"))
        self.label_3.setText(_translate("MainWindow", "Структурное подразделение:"))
        self.label_5.setText(_translate("MainWindow", "Акт №"))
        self.label_6.setText(_translate("MainWindow", "Дата"))
        self.label_16.setText(_translate("MainWindow", "ОКПО"))
        self.label_17.setText(_translate("MainWindow", "ОКДП"))
        self.label_21.setText(_translate("MainWindow", "ОКПО"))
        self.exportExcel.setText(_translate("MainWindow", "Экспорт"))
        self.exit.setText(_translate("MainWindow", "Выход"))
        self.label_2.setText(_translate("MainWindow", "О БОЕ, ЛОМЕ И УТРАТЕ ПОСУДЫ И ПРИБОРОВ"))


